version: "3"

services:
  web:
    image: haseebtariq368/flask-app:latest
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
